# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Kinosearch
version:      0.022
version_from: lib/Search/Kinosearch.pm
installdirs:  site
requires:
    Compress::Zlib:                1.33
    DB_File:                       0
    Digest::MD5:                   2.33
    Lingua::Stem::Snowball:        0.7
    Sort::External:                0.05
    String::CRC32:                 1.3
    Test::Exception:               0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
