# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Kinosearch
version:      0.03_02
version_from: lib/Search/Kinosearch.pm
installdirs:  site
requires:
    Class::WhiteHole:              0
    Compress::Zlib:                1.33
    DB_File:                       0
    Digest::MD5:                   2.33
    File::Temp:                    0.14
    Inline::C:                     0
    Lingua::Stem::Snowball:        0.7
    Sort::External:                0.04
    String::CRC32:                 1.3
    Test::Exception:               0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
